# Generated by Django 4.0.2 on 2022-09-12 15:38
from datetime import datetime
from django.db import migrations


def create_configuration(apps, schema_editor):
    Configuration = apps.get_model('core', 'Configuration')
    
    configuration = {
        'last_paid_comment': datetime.now()
    }

    Configuration.objects.create(**configuration)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_configuration),
    ]
