# Generated by Django 4.0.2 on 2022-11-03 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_failedtransaction_account_failedtransaction_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('permlink', models.CharField(max_length=512)),
                ('title', models.TextField()),
                ('created', models.DateTimeField()),
                ('vote_rshares', models.BigIntegerField()),
                ('total_payout_value', models.FloatField()),
                ('author_rewards', models.FloatField()),
                ('active_votes', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'member post',
                'verbose_name_plural': 'member posts',
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='failedtransaction',
            name='fail_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Account does not exist'), (2, 'Sponsor does not exist'), (3, 'Empty sponsee'), (4, 'Sponsee acount does not exist'), (5, 'Bad sponsee format'), (6, 'Not synced account'), (7, 'Not synced sponsor')]),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.CharField(max_length=50)),
                ('weight', models.BigIntegerField()),
                ('rshares', models.BigIntegerField()),
                ('percent', models.IntegerField()),
                ('reputation', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
                'ordering': ['time'],
            },
        ),
    ]
