# Generated by Django 4.0.2 on 2022-04-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member_comment_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_rshares',
            field=models.BigIntegerField(null=True),
        ),
    ]
