# Generated by Django 4.0.2 on 2022-04-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_member_total_rshares'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['account'], 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.AddField(
            model_name='member',
            name='next_upvote_estimate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='pending_balance',
            field=models.FloatField(default=0),
        ),
    ]
