# Generated by Django 4.0.2 on 2022-11-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_empty_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxDailyHivePerMVest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('hivesql_id', models.BigIntegerField(blank=True, null=True)),
                ('block_num', models.BigIntegerField(blank=True, null=True)),
                ('hive_per_mvest', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'maximum daily Hive per mvest',
                'verbose_name_plural': 'maximum daily Hive per mvest',
                'ordering': ['timestamp'],
            },
        ),
    ]
