# Generated by Django 4.0.2 on 2022-12-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_maxdailyhivepermvest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSyncOlderPostOriginalEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_enrollment', models.DateTimeField()),
            ],
        ),
    ]
