# Generated by Django 4.0.2 on 2022-04-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_member_options_member_next_upvote_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_shares',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
