# Generated by Django 4.0.2 on 2023-08-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lastsyncolderpostoriginalenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_beneficiaries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_beneficiaries',
            field=models.BooleanField(default=True),
        ),
    ]
