# Generated by Django 4.0.2 on 2022-05-25 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_member_total_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
            ],
            options={
                'verbose_name': 'sponsee',
                'verbose_name_plural': 'sponsees',
                'ordering': ['account'],
            },
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-total_shares'], 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField()),
                ('source', models.CharField(choices=[('mgmt', 'mgmt'), ('steembasicincome', 'steembasicincome'), ('sbi10', 'sbi10'), ('sbi9', 'sbi9'), ('sbi8', 'sbi8'), ('sbi7', 'sbi7'), ('sbi6', 'sbi6'), ('sbi5', 'sbi5'), ('sbi4', 'sbi4'), ('sbi3', 'sbi3'), ('sbi2', 'sbi2'), ('shares', 'shares')], max_length=50)),
                ('memo', models.TextField(blank=True, null=True)),
                ('shares', models.IntegerField(null=True)),
                ('vests', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('Valid', 'Valid'), ('Refunded', 'Refunded'), ('AccountDoesNotExist', 'AccountDoesNotExist'), ('Refused', 'Refused'), ('LessOrNoSponsee', 'LessOrNoSponsee')], max_length=50)),
                ('share_type', models.CharField(choices=[('Mgmt', 'Mgmt'), ('Standard', 'Standard'), ('Delegation', 'Delegation'), ('SBD', 'SBD'), ('Refund', 'Refund'), ('RemovedDelegation', 'RemovedDelegation'), ('DelegationLeased', 'DelegationLeased'), ('Refunded', 'Refunded'), ('MgmtTransfer', 'MgmtTransfer'), ('ShareTransfer', 'ShareTransfer'), ('HBD', 'HBD')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='account')),
                ('sponsees', models.ManyToManyField(blank=True, to='core.Sponsee', verbose_name='crops')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='core.member', verbose_name='sponsor')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='sponsee',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='account'),
        ),
    ]
