# Generated by Django 4.0.2 on 2022-05-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sponsee_alter_member_options_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTransactionSponsee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoonse_text', models.TextField(blank=True, null=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'failed transaction soopnse',
                'verbose_name_plural': 'failed transactions soopnse',
                'ordering': ['-transaction'],
            },
        ),
    ]
