# Generated by Django 4.0.2 on 2022-05-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_failedtransactionsponsee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sponsees',
        ),
        migrations.AddField(
            model_name='sponsee',
            name='trx',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.transaction', verbose_name='trx'),
            preserve_default=False,
        ),
    ]
