# Generated by Django 4.0.2 on 2023-08-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_beneficiaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='curator_payout_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='percent_hbd',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
