# Generated by Django 4.0.2 on 2022-05-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_transaction_sponsees_sponsee_trx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsee',
            name='trx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsees', to='core.transaction', verbose_name='trx'),
        ),
    ]
