# Generated by Django 4.0.2 on 2022-06-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sponsee_trx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('spoonse_text', models.TextField(blank=True, null=True)),
                ('is_solved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'failed transaction',
                'verbose_name_plural': 'failed transactions',
                'ordering': ['-transaction'],
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='index',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='FailedTransactionSponsee',
        ),
        migrations.AddField(
            model_name='failedtransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transaction', verbose_name='transaction'),
        ),
    ]
