# Generated by Django 4.0.2 on 2022-06-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_failedtransaction_fail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedtransaction',
            name='trx_index',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='failedtransaction',
            name='fail_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Account does not exist'), (2, 'Sponsor does not exist'), (3, 'Empty sponsee'), (4, 'Sponsee acount does not exist'), (5, 'Bad sponsee format'), (6, 'index already exists')]),
        ),
        migrations.AlterField(
            model_name='failedtransaction',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transaction', verbose_name='transaction'),
        ),
    ]
