version: "3.7"
services:
  app:
    image: ${IMAGE_SERVICE}
    volumes:
      - ./app:/app
    build:
      args:
        - DJANGO_ENV=dev
    ports:
      - "${PORT_DEBUG}:8009"
    command: ["sh", "/app/boot_scripts/dev.sh"]

  postgres:
    volumes:
      - db-data:/var/lib/postgresql/data/

  worker:
    environment:
      - DJANGO_SETTINGS_MODULE=hive_sbi_api.settings.dev
    build:
      args:
        - DJANGO_ENV=dev

  beat:
    environment:
      - DJANGO_SETTINGS_MODULE=hive_sbi_api.settings.dev
    build:
      args:
        - DJANGO_ENV=dev

volumes:
  db-data:
